language: python
sudo: false

python:
    - "3.6"

cache:
    pip: true

env:
    - USE_CYTHON=True

install:
    - pip install Cython
    - python setup.py install

script:
    - python -m unittest tests/*.py
